spring:
  jmx:
  enabled: false
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:h2:file:~/signup2
    driverClassName: org.h2.Driver
    username: sa
    password: completo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    user: sa
    password: completo
    schema: signup
    baseline-on-migrate: true
    locations:
      - classpath:db/migration